baseURL = "https://legal.zuzu.network"
languageCode = "ko"
DefaultContentLanguage = "ko"
title = "주주 리걸"
theme = "zuzu"
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs"
googleAnalytics = ""
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
author = "주주 리걸"
description = "주주총회·이사회 진행부터, 등기까지!"
signupURL = "https://legal-app.zuzu.network/signup"
loginURL = "https://legal-app.zuzu.network/login"
doNotLoadAnimations = false
googleSiteVerify = ""

[menu]

[[menu.main]]
identifier = "agendas"
name = "지원 안건"
url = "/agendas"
title = "지원 안건"
weight = 1

[[menu.main]]
identifier = "captial-change"
name = "자본금 변경"
url = "/agendas/capital-change/"
parent = "agendas"
title = "자본금 변경"
weight = 1

[[menu.main]]
identifier = "director-change"
name = "임원 변경"
url = "/agendas/director-change/"
parent = "agendas"
title = "임원 변경"
weight = 2

[[menu.main]]
identifier = "aoi-change"
name = "정관 변경"
url = "/agendas/aoi-change/"
parent = "agendas"
title = "정관 변경"
weight = 3

# [[menu.main]]
# identifier = "option"
# name = "스톡옵션"
# url = "/agendas/option/"
# parent = "agendas"
# title = "스톡옵션"
# weight = 4

# [[menu.main]]
# identifier = "documents"
# name = "생성 문서"
# title = "생성 문서"
# weight = 2

# [[menu.main]]
# identifier = "generated-document"
# name = "회사 등록 시 자동 생성 문서"
# url = "/documents/generated-document/"
# parent = "documents"
# title = "회사 등록 시 자동 생성 문서"
# weight = 1

# [[menu.main]]
# identifier = "template-document"
# name = "기본 문서 템플릿 다운로드"
# url = "/documents/template-document/"
# parent = "documents"
# title = "기본 문서 템플릿"
# weight = 2

[[menu.main]]
identifier = "resource"
name = "리소스"
url = "/resource"
title = "리소스"
weight = 5

[[menu.main]]
identifier = "resource-guide"
name = "주주 리걸 사용법"
url = "/resource/guide/"
title = "주주 리걸 사용법"
parent = "resource"
weight = 2

# [[menu.main]]
# identifier = "resource-team"
# name = "주주 팀 소개"
# url = "/resource/team/"
# title = "주주 팀 소개"
# parent = "resource"
# weight = 2

[[menu.main]]
identifier = "resource-recruit"
name = "채용"
url = "https://www.notion.so/f3710bea015740f8ad76941a30214635"
title = "채용"
parent = "resource"
weight = 1

[[menu.main]]
identifier = "resource-update"
name = "주주 블로그"
url = "https://blog.zuzu.network"
title = "주주 블로그"
parent = "resource"
weight = 3

[build]
noJSConfigInAssets = false
useResourceCacheWhen = "fallback"
writeStats = false

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[permalinks]
"/" = ":title"

[privacy]

[privacy.disqus]
disable = false

[privacy.googleAnalytics]
anonymizeIP = false
disable = false
respectDoNotTrack = false
useSessionStorage = false

[privacy.instagram]
disable = false
simple = false

[privacy.twitter]
disable = false
enableDNT = false
simple = false

[privacy.vimeo]
disable = false
enableDNT = false
simple = false

[privacy.youtube]
disable = false
privacyEnhanced = false

[caches]

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = -1

[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = -1

[caches.getjson]
dir = ":cacheDir/:project"
maxAge = -1

[caches.images]
dir = ":resourceDir/_gen"
maxAge = -1

[caches.modules]
dir = ":cacheDir/modules"
maxAge = -1

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = false

[minify.tdewolff]

[minify.tdewolff.css]
decimals = -1
keepCSS2 = true

[minify.tdewolff.html]
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = false

[minify.tdewolff.js]

[minify.tdewolff.json]

[minify.tdewolff.svg]
decimals = -1

[minify.tdewolff.xml]
keepWhitespace = false
