baseURL = "http://example.org/"
<<<<<<< HEAD
languageCode = "ko"
title = "ZUZU LEGAL LANDING"
=======
languageCode = "en-us"
title = "My New Hugo Site"
>>>>>>> c9cbced0fc469e4324430afc2717d4e954106920
theme = "ananke"
